# Generated by Django 5.2.7 on 2025-11-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={},
        ),
        migrations.AlterModelTable(
            name='userdevice',
            table='authentications_user_device',
        ),
    ]
