# Generated by Django 5.2.7 on 2025-11-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destination',
            table='authentications_destination',
        ),
        migrations.AlterModelTable(
            name='purpose',
            table='authentications_purpose',
        ),
    ]
