# Generated by Django 4.2.16 on 2025-11-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'purpose', 'code'], name='authenticat_user_id_0027e8_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_fef526_idx'),
        ),
    ]
