# Generated by Django 5.2.7 on 2025-11-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_remove_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
