# Generated by Django 5.2.7 on 2025-11-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_user_date_joined_user_is_active_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userverification',
            table='authentications_user_verification',
        ),
    ]
