# Generated by Django 5.1.6 on 2025-10-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_preference_remove_phone_country_phone_created_at'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.preference'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile',
        ),
        migrations.AlterModelTable(
            name='verified',
            table='authentication_verified',
        ),
    ]
