# Generated by Django 5.2.8 on 2025-11-18 05:50

import core.time.timestamps
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_public_id', models.UUIDField()),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(max_length=50)),
                ('expires_at', models.BigIntegerField()),
                ('created_at', models.BigIntegerField(default=core.time.timestamps.current_timestamp)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
