# Generated by Django 4.2.26 on 2025-11-18 22:42

import core.time.timestamps
import core.uuid.generate
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('expires_at', models.BigIntegerField()),
                ('id', models.UUIDField(default=core.uuid.generate.generate_code, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.BigIntegerField(default=core.time.timestamps.current_timestamp)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='otp.purpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
