# Generated by Django 5.2.8 on 2025-11-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_remove_verificationcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='public_id',
            field=models.UUIDField(),
        ),
    ]
