# Generated by Django 5.2.8 on 2025-11-19 06:06

import core.uuid.generate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_alter_verificationcode_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='link',
            field=models.CharField(default=core.uuid.generate.generate_code),
        ),
    ]
