# Generated by Django 5.1.6 on 2025-10-03 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='country',
        ),
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
