# Generated by Django 5.1.6 on 2025-09-30 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core2.validityperiod')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core2.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
